/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull cm-website'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 2
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest)
 *
 * [Full Setup Instructions](https://data.eu.amplitude.com/tmlmobilidade/default/implementation/cm-website)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'default';

export const ApiKey: Record<Environment, string> = {
  default: '66aabe34bf2c52425e3dd7ab51c683e1'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '2',
    branch: 'main',
    source: 'cm-website',
    versionId: 'c1eb6e9c-4fdb-4e52-a3e8-6bca97569cf4'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0'
    }
  },
  serverZone: amplitude.Types.ServerZone.EU
};

export interface LoadOptionsBase { disabled?: boolean }

export type LoadOptionsWithEnvironment = LoadOptionsBase & { environment: Environment; client?: { configuration?: BrowserOptions; }; };
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions; } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient; } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface IdentifyProperties {
  referrer?: string;
  referring_domain?: string;
}

export interface AddFavoriteLineProperties {
  /**
   * Holds a the ID of the entity "Line", which is usually a 4-digit numeric string.
   */
  line_id: string;
}

export interface AddFavoriteStopProperties {
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export interface AlertClickedProperties {
  "[Amplitude] Page Path"?: any;
  /**
   * Id of an Alert
   */
  alert_id: string;
  /**
   * Title of a Alert
   */
  alert_title: string;
}

export interface AlertsFilterChangedProperties {
  /**
   * Captures a filter type
   */
  filter_type: string;
  /**
   * Stores a filter value
   */
  filter_value: string;
}

export interface CaptureAlertsRefererProperties {
  page_referer: string;
}

export interface CaptureFrontendErrorProperties {
  "[Amplitude] Page Path"?: any;
  /**
   * Captures an error date
   */
  error_date: string;
  /**
   * Error text
   */
  error_title: string;
  /**
   * Captures an Error type
   */
  error_type: string;
}

export interface CaptureNewsRefererProperties {
  /**
   * Captures the Referrer for a page
   */
  page_referer: string;
}

export interface ChangeStopsViewTypeProperties {
  /**
   * Type of listing data
   */
  view_type: string;
}

export interface ClickDebugToggleProperties {
  /**
   * Captures if something is enabled
   */
  is_enabled: string;
}

export interface ClickLinkProperties {
  /**
   * This property indicates the location in the app (the pathname, the screen id) where the current event was generated at.
   */
  current_page: string;
  /**
   * This property indicates the href of the destination URL. This is used when the user is navigating out of the current screen by means of a link (either in-app or in a website).
   */
  destination_href: string;
}

export interface DatePeriodSelectedProperties {
  /**
   * Captures a date value
   */
  date_value: string;
}

export interface GithubClickedProperties {
  /**
   * Captures a click
   */
  click: string;
}

export interface LostAndFoundAreaClickedProperties {
  /**
   * Type of contact device
   */
  action_type: string;
  /**
   * Captures a clicked area
   */
  area_clicked: string;
}

export interface OpenCardViagem2024Properties {
  /**
   * Id of a card
   */
  card_id: string;
  /**
   * Captures a Card Title
   */
  card_title: string;
}

export interface OpenGoogleMapsClickedProperties {
  "[Amplitude] Page Location"?: any;
  "[Amplitude] Page Path"?: any;
  /**
   * Captures the URL of the page where the element was clicked.
   *
   * For example, a value of https://www.amplitude.com means that the element clicked was on this page.
   */
  "[Amplitude] Page URL"?: any;
  /**
   * Captures a click
   */
  click: string;
  /**
   * Clicked somekind of contact form
   */
  click_from: string;
}

export interface PingProperties {
  /**
   * The version of the application that generated the event.
   */
  app_version: string;
  /**
   * This property indicates the location in the app (the pathname, the screen id) where the current event was generated at.
   */
  current_page: string;
}

export interface PlannerUsedProperties {
  /**
   * Captures if a planner card has been clicked
   */
  planner_clicked: string;
}

export interface RemoveFavoriteLineProperties {
  /**
   * Holds a the ID of the entity "Line", which is usually a 4-digit numeric string.
   */
  line_id: string;
}

export interface RemoveFavoriteStopProperties {
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export interface SearchAlertProperties {
  /**
   * Captures a Search Value
   */
  search_value: string;
}

export interface SearchLineProperties {
  /**
   * Captures a Search Value
   */
  search_value: string;
}

export interface SearchStopProperties {
  search_value: string;
}

export interface ShareCardViagem2024Properties {
  card_id: string;
  card_title: string;
}

export interface StopAudioPlayedProperties {
  /**
   * Captures when the audio is played
   */
  audio_played: string;
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export interface StopDetailRedirectedProperties {
  "[Amplitude] Page Path"?: any;
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
