/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull cm-website'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 2
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest)
 *
 * [Full Setup Instructions](https://data.eu.amplitude.com/tmlmobilidade/default/implementation/cm-website)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'default';

export const ApiKey: Record<Environment, string> = {
  default: '66aabe34bf2c52425e3dd7ab51c683e1'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '2',
    branch: 'main',
    source: 'cm-website',
    versionId: 'c1eb6e9c-4fdb-4e52-a3e8-6bca97569cf4'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0'
    }
  },
  serverZone: amplitude.Types.ServerZone.EU
};

export interface LoadOptionsBase { disabled?: boolean }

export type LoadOptionsWithEnvironment = LoadOptionsBase & { environment: Environment; client?: { configuration?: BrowserOptions; }; };
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions; } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient; } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface IdentifyProperties {
  referrer?: string;
  referring_domain?: string;
}

export interface AddFavoriteLineProperties {
  /**
   * Holds a the ID of the entity "Line", which is usually a 4-digit numeric string.
   */
  line_id: string;
}

export interface AddFavoriteStopProperties {
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export interface AlertClickedProperties {
  "[Amplitude] Page Path"?: any;
  alert_id: string;
  alert_title: string;
}

export interface CaptureAlertsRefererProperties {
  page_referer: string;
}

export interface CaptureFrontendErrorProperties {
  "[Amplitude] Page Path"?: any;
  error_date: string;
  error_title: string;
  error_type: string;
}

export interface CaptureNewsRefererProperties {
  page_referer: string;
}

export interface ChangeStopsViewTypeProperties {
  view_type: string;
}

export interface ClickDebugToggleProperties {
  is_enabled: string;
}

export interface ClickLinkProperties {
  /**
   * This property indicates the location in the app (the pathname, the screen id) where the current event was generated at.
   */
  current_page: string;
  /**
   * This property indicates the href of the destination URL. This is used when the user is navigating out of the current screen by means of a link (either in-app or in a website).
   */
  destination_href: string;
}

export interface DatePeriodSelectedProperties {
  "[Amplitude] Page Path"?: any;
  /**
   * Captures the page title of the page where the element was clicked.
   *
   * For example, if the page where the element was clicked has: <title>Amplitude</title>
   *
   * The value would be: Amplitude
   */
  "[Amplitude] Page Title"?: any;
  date_value: string;
}

export interface OpenCardViagem2024Properties {
  card_id: string;
  card_title: string;
}

export interface PingProperties {
  /**
   * The version of the application that generated the event.
   */
  app_version: string;
  /**
   * This property indicates the location in the app (the pathname, the screen id) where the current event was generated at.
   */
  current_page: string;
}

export interface RemoveFavoriteLineProperties {
  /**
   * Holds a the ID of the entity "Line", which is usually a 4-digit numeric string.
   */
  line_id: string;
}

export interface RemoveFavoriteStopProperties {
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export interface SearchLineProperties {
  search_value: string;
}

export interface SearchStopProperties {
  search_value: string;
}

export interface ShareCardViagem2024Properties {
  card_id: string;
  card_title: string;
}

export interface StopDetailRedirectedProperties {
  "[Amplitude] Page Path"?: any;
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export interface StopProbeQuestion1Properties {
  answer: string;
  answer_date: string;
  question_id: string;
  question_title: string;
}

export interface StopProbeQuestion2Properties {
  answer: string;
  answer_date: string;
  question_id: string;
  question_title: string;
}

export interface StopProbeQuestion3Properties {
  answer: string;
  answer_date: string;
  question_id: string;
  question_title: string;
}

export interface StopProbeQuestion4Properties {
  answer: string;
  answer_date: string;
  question_id: string;
  question_title: string;
}

export interface StopSelectedProperties {
  /**
   * Holds a the ID of the entity "Stop", which is always a 6-digit numeric string.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Length | 6 |
   * | Max Length | 6 |
   */
  stop_id: string;
}

export interface Viagem2024QuizAnsweredProperties {
  question_1?: string;
  question_10?: string;
  question_2?: string;
  question_3?: string;
  question_4?: string;
  question_5?: string;
  question_6?: string;
  question_7?: string;
  question_8?: string;
  question_9?: string;
}

export class Identify implements BaseEvent {
  event_type = amplitude.Types.SpecialEventType.IDENTIFY;

  constructor(
    public event_properties?: IdentifyProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class AcceptAnalyticsConsent implements BaseEvent {
  event_type = 'Accept Analytics Consent';
}

export class AddFavoriteLine implements BaseEvent {
  event_type = 'Add Favorite Line';

  constructor(
    public event_properties: AddFavoriteLineProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class AddFavoriteStop implements BaseEvent {
  event_type = 'Add Favorite Stop';

  constructor(
    public event_properties: AddFavoriteStopProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class AlertClicked implements BaseEvent {
  event_type = 'Alert Clicked';

  constructor(
    public event_properties: AlertClickedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class CaptureAlertsReferer implements BaseEvent {
  event_type = 'Capture Alerts Referer';

  constructor(
    public event_properties: CaptureAlertsRefererProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class CaptureFrontendError implements BaseEvent {
  event_type = 'Capture Frontend Error';

  constructor(
    public event_properties: CaptureFrontendErrorProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class CaptureNewsReferer implements BaseEvent {
  event_type = 'Capture News Referer';

  constructor(
    public event_properties: CaptureNewsRefererProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ChangeStopsViewType implements BaseEvent {
  event_type = 'Change Stops View Type';

  constructor(
    public event_properties: ChangeStopsViewTypeProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ClickDebugToggle implements BaseEvent {
  event_type = 'Click Debug Toggle';

  constructor(
    public event_properties: ClickDebugToggleProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ClickLink implements BaseEvent {
  event_type = 'Click Link';

  constructor(
    public event_properties: ClickLinkProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class DatePeriodSelected implements BaseEvent {
  event_type = 'Date Period Selected';

  constructor(
    public event_properties: DatePeriodSelectedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class OpenCardViagem2024 implements BaseEvent {
  event_type = 'Open Card Viagem 2024';

  constructor(
    public event_properties: OpenCardViagem2024Properties,
  ) {
    this.event_properties = event_properties;
  }
}

export class Ping implements BaseEvent {
  event_type = 'Ping';

  constructor(
    public event_properties: PingProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class RemoveFavoriteLine implements BaseEvent {
  event_type = 'Remove Favorite Line';

  constructor(
    public event_properties: RemoveFavoriteLineProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class RemoveFavoriteStop implements BaseEvent {
  event_type = 'Remove Favorite Stop';

  constructor(
    public event_properties: RemoveFavoriteStopProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class SearchLine implements BaseEvent {
  event_type = 'Search Line';

  constructor(
    public event_properties: SearchLineProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class SearchStop implements BaseEvent {
  event_type = 'Search Stop';

  constructor(
    public event_properties: SearchStopProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ShareCardViagem2024 implements BaseEvent {
  event_type = 'Share Card Viagem 2024';

  constructor(
    public event_properties: ShareCardViagem2024Properties,
  ) {
    this.event_properties = event_properties;
  }
}

export class StopDetailRedirected implements BaseEvent {
  event_type = 'Stop Detail Redirected';

  constructor(
    public event_properties: StopDetailRedirectedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class StopProbeQuestion1 implements BaseEvent {
  event_type = 'Stop Probe Question 1';

  constructor(
    public event_properties: StopProbeQuestion1Properties,
  ) {
    this.event_properties = event_properties;
  }
}

export class StopProbeQuestion2 implements BaseEvent {
  event_type = 'Stop Probe Question 2';

  constructor(
    public event_properties: StopProbeQuestion2Properties,
  ) {
    this.event_properties = event_properties;
  }
}

export class StopProbeQuestion3 implements BaseEvent {
  event_type = 'Stop Probe Question 3';

  constructor(
    public event_properties: StopProbeQuestion3Properties,
  ) {
    this.event_properties = event_properties;
  }
}

export class StopProbeQuestion4 implements BaseEvent {
  event_type = 'Stop Probe Question 4';

  constructor(
    public event_properties: StopProbeQuestion4Properties,
  ) {
    this.event_properties = event_properties;
  }
}

export class StopSelected implements BaseEvent {
  event_type = 'Stop Selected';

  constructor(
    public event_properties: StopSelectedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class Viagem2024QuizAnswered implements BaseEvent {
  event_type = 'Viagem 2024 Quiz Answered';

  constructor(
    public event_properties?: Viagem2024QuizAnsweredProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already intialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param properties The user properties.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    properties?: IdentifyProperties,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    const eventProperties = properties;
    if (eventProperties != null) {
      for (const [key, value] of Object.entries(eventProperties)) {
        amplitudeIdentify.set(key, value);
      }
    }
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * Accept Analytics Consent
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Accept%20Analytics%20Consent)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  acceptAnalyticsConsent(
    options?: EventOptions,
  ) {
    return this.track(new AcceptAnalyticsConsent(), options);
  }

  /**
   * Add Favorite Line
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Add%20Favorite%20Line)
   *
   * Event to track when a user adds a public transportation line to their list of favorites for quick access and personalized recommendations.
   *
   * @param properties The event's properties (e.g. line_id)
   * @param options Amplitude event options.
   */
  addFavoriteLine(
    properties: AddFavoriteLineProperties,
    options?: EventOptions,
  ) {
    return this.track(new AddFavoriteLine(properties), options);
  }

  /**
   * Add Favorite Stop
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Add%20Favorite%20Stop)
   *
   * Event to track when a user adds a stop to their favorites list.
   *
   * @param properties The event's properties (e.g. stop_id)
   * @param options Amplitude event options.
   */
  addFavoriteStop(
    properties: AddFavoriteStopProperties,
    options?: EventOptions,
  ) {
    return this.track(new AddFavoriteStop(properties), options);
  }

  /**
   * Alert Clicked
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Alert%20Clicked)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. [Amplitude] Page Path)
   * @param options Amplitude event options.
   */
  alertClicked(
    properties: AlertClickedProperties,
    options?: EventOptions,
  ) {
    return this.track(new AlertClicked(properties), options);
  }

  /**
   * Capture Alerts Referer
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Capture%20Alerts%20Referer)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. page_referer)
   * @param options Amplitude event options.
   */
  captureAlertsReferer(
    properties: CaptureAlertsRefererProperties,
    options?: EventOptions,
  ) {
    return this.track(new CaptureAlertsReferer(properties), options);
  }

  /**
   * Capture Frontend Error
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Capture%20Frontend%20Error)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. [Amplitude] Page Path)
   * @param options Amplitude event options.
   */
  captureFrontendError(
    properties: CaptureFrontendErrorProperties,
    options?: EventOptions,
  ) {
    return this.track(new CaptureFrontendError(properties), options);
  }

  /**
   * Capture News Referer
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Capture%20News%20Referer)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. page_referer)
   * @param options Amplitude event options.
   */
  captureNewsReferer(
    properties: CaptureNewsRefererProperties,
    options?: EventOptions,
  ) {
    return this.track(new CaptureNewsReferer(properties), options);
  }

  /**
   * Change Stops View Type
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Change%20Stops%20View%20Type)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. view_type)
   * @param options Amplitude event options.
   */
  changeStopsViewType(
    properties: ChangeStopsViewTypeProperties,
    options?: EventOptions,
  ) {
    return this.track(new ChangeStopsViewType(properties), options);
  }

  /**
   * Click Debug Toggle
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Click%20Debug%20Toggle)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. is_enabled)
   * @param options Amplitude event options.
   */
  clickDebugToggle(
    properties: ClickDebugToggleProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickDebugToggle(properties), options);
  }

  /**
   * Click Link
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Click%20Link)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. current_page)
   * @param options Amplitude event options.
   */
  clickLink(
    properties: ClickLinkProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickLink(properties), options);
  }

  /**
   * Date Period Selected
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Date%20Period%20Selected)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. [Amplitude] Page Path)
   * @param options Amplitude event options.
   */
  datePeriodSelected(
    properties: DatePeriodSelectedProperties,
    options?: EventOptions,
  ) {
    return this.track(new DatePeriodSelected(properties), options);
  }

  /**
   * Open Card Viagem 2024
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Open%20Card%20Viagem%202024)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. card_id)
   * @param options Amplitude event options.
   */
  openCardViagem2024(
    properties: OpenCardViagem2024Properties,
    options?: EventOptions,
  ) {
    return this.track(new OpenCardViagem2024(properties), options);
  }

  /**
   * Ping
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Ping)
   *
   * Event to track when a user visits CMetropolitana website.
   *
   * @param properties The event's properties (e.g. app_version)
   * @param options Amplitude event options.
   */
  ping(
    properties: PingProperties,
    options?: EventOptions,
  ) {
    return this.track(new Ping(properties), options);
  }

  /**
   * Remove Favorite Line
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Remove%20Favorite%20Line)
   *
   * Event to track when a user removes a specific public transportation line from their list of favorites.
   *
   * @param properties The event's properties (e.g. line_id)
   * @param options Amplitude event options.
   */
  removeFavoriteLine(
    properties: RemoveFavoriteLineProperties,
    options?: EventOptions,
  ) {
    return this.track(new RemoveFavoriteLine(properties), options);
  }

  /**
   * Remove Favorite Stop
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Remove%20Favorite%20Stop)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. stop_id)
   * @param options Amplitude event options.
   */
  removeFavoriteStop(
    properties: RemoveFavoriteStopProperties,
    options?: EventOptions,
  ) {
    return this.track(new RemoveFavoriteStop(properties), options);
  }

  /**
   * Search Line
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Search%20Line)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. search_value)
   * @param options Amplitude event options.
   */
  searchLine(
    properties: SearchLineProperties,
    options?: EventOptions,
  ) {
    return this.track(new SearchLine(properties), options);
  }

  /**
   * Search Stop
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Search%20Stop)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. search_value)
   * @param options Amplitude event options.
   */
  searchStop(
    properties: SearchStopProperties,
    options?: EventOptions,
  ) {
    return this.track(new SearchStop(properties), options);
  }

  /**
   * Share Card Viagem 2024
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Share%20Card%20Viagem%202024)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. card_id)
   * @param options Amplitude event options.
   */
  shareCardViagem2024(
    properties: ShareCardViagem2024Properties,
    options?: EventOptions,
  ) {
    return this.track(new ShareCardViagem2024(properties), options);
  }

  /**
   * Stop Detail Redirected
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Stop%20Detail%20Redirected)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. [Amplitude] Page Path)
   * @param options Amplitude event options.
   */
  stopDetailRedirected(
    properties: StopDetailRedirectedProperties,
    options?: EventOptions,
  ) {
    return this.track(new StopDetailRedirected(properties), options);
  }

  /**
   * Stop Probe Question 1
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Stop%20Probe%20Question%201)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. answer)
   * @param options Amplitude event options.
   */
  stopProbeQuestion1(
    properties: StopProbeQuestion1Properties,
    options?: EventOptions,
  ) {
    return this.track(new StopProbeQuestion1(properties), options);
  }

  /**
   * Stop Probe Question 2
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Stop%20Probe%20Question%202)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. answer)
   * @param options Amplitude event options.
   */
  stopProbeQuestion2(
    properties: StopProbeQuestion2Properties,
    options?: EventOptions,
  ) {
    return this.track(new StopProbeQuestion2(properties), options);
  }

  /**
   * Stop Probe Question 3
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Stop%20Probe%20Question%203)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. answer)
   * @param options Amplitude event options.
   */
  stopProbeQuestion3(
    properties: StopProbeQuestion3Properties,
    options?: EventOptions,
  ) {
    return this.track(new StopProbeQuestion3(properties), options);
  }

  /**
   * Stop Probe Question 4
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Stop%20Probe%20Question%204)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. answer)
   * @param options Amplitude event options.
   */
  stopProbeQuestion4(
    properties: StopProbeQuestion4Properties,
    options?: EventOptions,
  ) {
    return this.track(new StopProbeQuestion4(properties), options);
  }

  /**
   * Stop Selected
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Stop%20Selected)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. stop_id)
   * @param options Amplitude event options.
   */
  stopSelected(
    properties: StopSelectedProperties,
    options?: EventOptions,
  ) {
    return this.track(new StopSelected(properties), options);
  }

  /**
   * Viagem 2024 Quiz Answered
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/tmlmobilidade/default/events/main/latest/Viagem%202024%20Quiz%20Answered)
   *
   * Event used to track answersEvent to track when a user answers a quiz question related to the Viagem 2024 campaign.
   *
   * @param properties The event's properties (e.g. question_1)
   * @param options Amplitude event options.
   */
  viagem2024QuizAnswered(
    properties?: Viagem2024QuizAnsweredProperties,
    options?: EventOptions,
  ) {
    return this.track(new Viagem2024QuizAnswered(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
