# # #

name: cmet-website

volumes:
  certbotdata:

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    image: ghcr.io/carrismetropolitana/website-nginx:test
    restart: unless-stopped
    mem_limit: 1g
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./nginx/uptime.conf:/etc/nginx/uptime.conf
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''