# # #

name: cmet-website-development

volumes:
  websitedbdata:

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  websitedb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 69001:27017
    volumes:
      - websitedbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=websitedbuser
      - MONGO_INITDB_ROOT_PASSWORD=websitedbpassword